### ISSUE TITLE
# output csv files from step1 were empty!

### ISSUE THREAD

**Issue by cbiOPela** [seasky002002/Strandscript#1]
Hi all!

When using your amazing tool towards the readme file, i find all the output as empty files (0 kb). Apparently, installation procedures were OK. Also, the output of test.modules looks well.
Could you please give me some advice to solve that?

Best Regards

**Comment by seasky002002** [comment]
Would you please share some lines of your manifest file?

**Comment by cbiOPela** [comment]
pelayo@biopelayo-SATELLITE-C50D-B:~/Escritorio/ICM$ head -60 GSA-24v2-0_A1.csv 

Illumina, Inc.
[Heading]
Descriptor File Name,GSA-24v2-0_A1.bpm
Assay Format,Infinium HTS
Date Manufactured,3/15/2018
Loci Count ,665608
[Assay]
IlmnID,Name,IlmnStrand,SNP,AddressA_ID,AlleleA_ProbeSeq,AddressB_ID,AlleleB_ProbeSeq,GenomeBuild,Chr,MapInfo,Ploidy,Species,Source,SourceVersion,SourceStrand,SourceSeq,TopGenomicSeq,BeadSetID,Exp_Clusters,Intensity_Only,RefStrand
1:103380393-0_B_R_2346041316,1:103380393,BOT,[T/C],0094724281,AATAAACTTTTATGCAAAACTTGTAAGATAACTCTTCTTTCCTTCTTCTT,,,37,1,103380393,diploid,Homo sapiens,1000genomes,0,TOP,GCTTCCCCTTTCTCTCCTCTTTCTCCTTTGGGACCCTAAACAATGTTAAAAAAAAAAAAA[A/G]AAGAAGAAGGAAAGAAGAGTTATCTTACAAGTTTTGCATAAAAGTTTATTAACCTTGGCA,GCTTCCCCTTTCTCTCCTCTTTCTCCTTTGGGACCCTAAACAATGTTAAAAAAAAAAAAA[A/G]AAGAAGAAGGAAAGAAGAGTTATCTTACAAGTTTTGCATAAAAGTTTATTAACCTTGGCA,1355,3,0,-
1:109439680-0_T_F_2348625138,1:109439680,TOP,[A/G],0095666109,GTTGGGCAATGCTTATTTCTATTTGCATGATTATGCCAAAGCATTAGAAT,,,37,1,109439680,diploid,Homo sapiens,1000genomes,0,TOP,TTTACAGCCAGTTGGGCAATGCTTATTTCTATTTGCATGATTATGCCAAAGCATTAGAAT[A/G]TCACCATCATGATTTAACCCTTGCAAGGTAATTAATTTAAGCTTTTAAATATTCTTCCTT,TTTACAGCCAGTTGGGCAATGCTTATTTCTATTTGCATGATTATGCCAAAGCATTAGAAT[A/G]TCACCATCATGATTTAACCCTTGCAAGGTAATTAATTTAAGCTTTTAAATATTCTTCCTT,1382,3,0,+

**Comment by seasky002002** [comment]
The manifest file looks good.
Please make sure the manifest file in linux format. (use dos2unix GSA-24v2-0_A1.csv)
Please check if you have hg19.fa under folder fasta/
If the issue still there, would you mind send me your manifest file, or put some where that I can dowload it? My email seasky002002@gmail.com.

**Comment by seasky002002** [comment]
I can download the manifest from illumina. Will test and let you know.

**Comment by seasky002002** [comment]
I tested step1 and everything ran well. 
Here is the command line I used:
![image](https://user-images.githubusercontent.com/10885314/53604489-45867780-3b7a-11e9-84da-0d6983a6a8f3.png)
And here are the two output files created by step1:
![image](https://user-images.githubusercontent.com/10885314/53604597-867e8c00-3b7a-11e9-97fa-2b5ab4a3d441.png)

**Comment by cbiOPela** [comment]
Thank you for your rapid help. This is what i get right now:
#
pelayo@biopelayo-SATELLITE-C50D-B:~/Strandscript-master/test$ cd .. && perl ./bin/step1-mismatch.pl -o test/ -n GSA-24v2-0_A1 -in ./example/GSA-24v2-0_A1.csv 
Out of memory!
Program exist with Error
#

Is it due to the fact of memory RAM capacities? Could you please share the output files you get?

**Comment by seasky002002** [comment]
Please see the output files at https://www.dropbox.com/sh/2jv15kwjriutp6y/AABlsCnmMWuWCyu11t96NsXfa?dl=0

**Comment by cbiOPela** [comment]
Thank You!!

**Comment by FMinnai** [comment]
Hello! 
unfortunately I am encountered the same problem: after launching the Step1, I obtained an empty Step1 output.
It seems that my manifest file is ok...
Anyone that could help me?
Thank you,

Francesca M

**Comment by TianTTL** [comment]
> Hello! unfortunately I am encountered the same problem: after launching the Step1, I obtained an empty Step1 output. It seems that my manifest file is ok... Anyone that could help me? Thank you,
> 
> Francesca M

I had the same problem recently and tried to fix it. 
 I found out that the possible reason is that the hg19/38 reference genomes downloaded from UCSC are in .fa.gz format by default, and StrandScript can't handle them directly. 
After unzipping them into the /fasta directory under the Strandscript path (make sure the reference genomes are in .fa format at this point), step1 runs correctly.
Hope this helps. @FMinnai
