### ISSUE TITLE
Please add a licence

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [seasky002002/Strandscript#3]
I would like to use Stranscript in my project, but it does not have a license so I do not know if this is allowed. Can you add a license to this project?

**Comment by seasky002002** [comment]
Thank you so much for using StrandScript! It’s free. Please feel free to
use it.

Thanks,
Jing

**Comment by AskPascal** [comment]
Nice to see. 
But does this mean any of these:
* [CC0](https://creativecommons.org/publicdomain/zero/1.0/)
* [MIT](https://choosealicense.com/licenses/mit/)
* [Unlicense](https://choosealicense.com/licenses/unlicense/)

Or are there any other restrictions in how people are allowed to use and build upon your work?

**Comment by seasky002002** [comment]
It’s MIT license. No other restrictions.

Thank you!

**Comment by AskPascal** [comment]
Thanks for the clarification

**Comment by Redmar-van-den-Berg** [comment]
Thanks!
